version: "3.8"

services:
  app:
    build: .
    container_name: "api-node"
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    networks:
      - todo-app-networks
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=livraria
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    networks:
      - todo-app-networks

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_AUTH_USERNAME=root
      - ME_CONFIG_AUTH_PASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    networks:
      - todo-app-networks
    depends_on:
      - mongo

networks:
  todo-app-networks:
    driver: bridge
    